### ISSUE TITLE
Can we detect generated file like VSCode or Jetbrains do?

### ISSUE THREAD

**Issue by frederikhors** [ultraware/funlen#11]
Can we detect generated file like VSCode or Jetbrains do?

Using top line in file like: `// Code partially generated.` or `// Code generated by xxx, DO NOT EDIT.`.

In generated files we can have very long functions.

**Comment by martialblog** [comment]
This might be better solved with `exclude-rules` in the .golangci.yml config 

```yaml
issues:
  exclude-rules:
    - path: path/to/generated/code.go
      linters:
        - funlen
```

**Comment by martialblog** [comment]
@robinknaapen You think this is also solved with https://github.com/ultraware/funlen/pull/18 ?

**Comment by robinknaapen** [comment]
@frederikhors 

I thought that golangci-lint already ignored generated files by default. The following example does not trigger funlen

Given this basic config
```yaml
linters:
  disable-all: true
  enable:
    - funlen
 
linters-settings:
  funlen:
    lines: 5
    statements: 10
```

And this code

`main.go`
```golang
package main

import "fmt"

func main() {
	fmt.Println(Generated())
}
```

`generated.go`
```golang
// Code generated by Crow, DO NOT EDIT

package main

func Generated() string {
	// I have a lot of
	// comments
	// This will trigger the linter
	//
	//
	// for sure :)

	return "generated"
}
```
